apps/review/views.py
apps/session/views.py
static/js/review/components/review.js
templates/review/components/review.html
templates/review/lastcomment.html

issue 93 fixed

---

apps/review/views.py

Fix #102 포탈 연동 안되어 있을 때 연결 페이지 링크 text 수정

Fix #102 포탈 연동 안되어 있을 때 연결 페이지 링크 text 수정

---

apps/review/views.py

Hot fix #107 Http404 import error in apps.review.view

---

apps/review/views.py
templates/review/400.html
templates/review/403.html

#125 : 과목 사전 에러 핸들링 페이지
error handling view function: bad_request, permission_denied
error handling html 400.html, 403.html 
added

과목사전 에러 핸들링 페이지 이슈 해결

---

.gitignore
apps/session/models.py
otlplus/settings.py

modify settings.py
add settings_local.py in .gitignore
in the settings_local.py, add test DB information

setup test DB

---

requirements.txt

Add packages required to access test db server

---

apps/timetable/urls.py
apps/timetable/views.py
otlplus/urls.py
static/css/timetable/table.css
static/css/timetable/timetable.css
templates/components/header.html
templates/timetable/base.html
templates/timetable/index.html
templates/timetable/layout.html

basic front page를 만들었는데 lecture list가 안뜨고있어요
#137

issue#131 basic front page

---

static/css/review/insert.css
templates/review/insert.html

업로드 버튼을 ajax시켰다. 업로드 버튼 클릭 시 page refresh없이
삭제버튼이 나타나고, 'yeah.'라는 flash message를 1초동안 띄운다.(디자인
수정 필요) (issue 85)

issue #85 fixed 업로드 버튼 클릭시 메시지 띄움

---

apps/session/models.py

저번에 실수로  review 브랜치에 추가해서 다시 올립니다.

BlockColor model class 추가

---

templates/components/header.html
templates/review/lastcomment.html
templates/review/sresult.html

Issue #127 (좋아요 누른 표시가 자동 스크롤로 불러온 후기에 대해서는 되지 않는 문제)와 관련해서는 templates/review/lastcomment.html과 sresult.html에서 ajax로 갱신하는 과정에서 Issue #93 (이미 좋아요를 누른 게시글에 대한 피드백)에서 적용되었던 새로운 방식을 적용하지 않아 발생한 문제였습니다. 이를 해결하기 위해 class에 리뷰 번호를 추가시켰습니다. (주석은 크게 필요하다고 생각하지 않아 달지는 않았습니다)
그리고 왜 수정됐는지 모르겠는 부분들은 Indentation 수정입니다!

Fix issue #127(좋아요 누른 표시가 자동 스크롤로 불러온 후기에 대해서는 되지 않는 문제) and #86(OTL 과목사전 링크)

---

apps/review/views.py
templates/review/components/review.html
templates/review/lastcomment.html
templates/review/sresult.html

Issue #139 에 나와있는 내용 (코멘트에서 보이는 내용에 학기 추가)을 수행하였습니다.
자세한 것은 Issue 항목의 스샷 참고

Fixed Issue #139 (코멘트에서 보이는 내용에 학기 추가)

---

apps/session/views.py

Check if sparcsso is online before redirecting  #144

---

static/css/timetable/timetable.css
templates/timetable/index.html
templates/timetable/layout.html

디자인을 프론트로 옮기는 중입니다. (미완성)
일단 1920*1080 해상도를 먼저 만들고 있는데, 윈도우 기준으로 작업표시줄과 크롬 상단부의 북마크 등으로 인해, 페이지가 한 화면에 다 들어가지 않아 디자인에 없던 스크롤이 생겼습니다 (사진은 전체화면 모드로 전환한 상태로, 전체화면에서는 한 화면에 다 들어가게 해놨습니다.)

front page

---

apps/review/models.py
apps/session/models.py
apps/session/sparcssso.py
apps/session/views.py
otlplus/settings.py
templates/session/settings.html

sparcs sso v2 회원 탈퇴 기능을 구현했습니다.
모델의 수정을 포함합니다.

SSO v2 unregister 구현

---

apps/session/views.py
otlplus/settings.py
static/js/components/header.js
templates/session/settings.html

기존에 GET으로 unregister를 처리해 보안에 취약했던 부분을 패치했습니다.

unregister할 때 csrf 문제 대응

---

.gitignore
otlplus/settings.py

test DB를 사용하기 위해 settings.py 파일을 수정했습니다.
자세한 설정 등은 settings_local.py 파일을 통해 이루어집니다.
settings_local.py는 password, secret key 등의 정보를 저장하기 위한 파일로, git을 통해 공유하지 않습니다.

test DB setting

---

apps/review/urls.py
apps/review/views.py
apps/session/urls.py
apps/subject/management/commands/import-scholardb.py
apps/subject/models.py
apps/subject/urls.py
apps/timetable/urls.py
db_update_script.sh
otlplus/urls.py

현재 처리한 것은 Django110Warning이 계속 나왔었던 urls.py들을 수정한 것입니다.
실제 Django 1.10과 대응되는지 확인하기 위해서, Django 1.10을 virtualenv에 설치하여 사용하였습니다!
그 결과 현재 문제점은 다음과 같습니다.
(현재 문제점은 수정 완료된 것 같습니다. 문제점이 추가로 생기면 얼마든지 말씀해주세요!)
2016. 08. 24 추가!!!

[GUIDELINE] FIXED ISSUES ABOUT UPDATING Django (FIXED #159 AND #161)

---

apps/timetable/views.py
otlplus/settings.py
requirements.txt
static/css/timetable/timetable.css
templates/timetable/index.html
templates/timetable/index.jade
templates/timetable/layout.html

django에 jade적용하고, 기존 프론트파일 jade포멧으로 변경했어요

Convert html front to jade format

---

apps/session/urls.py
apps/timetable/views.py
otlplus/settings.py
otlplus/urls.py
requirements.txt
templates/test.jade
templates/timetable/index.jade
utils/__init__.py
utils/context_processors/__init__.py
utils/decorators.py
utils/forms.py
utils/management/commands/sybase_shell.py
utils/middleware.py
utils/models.py
utils/templatetags/forms.py
utils/templatetags/yearterm.py

이제 런서버가 가능하지만 로그인 버튼을 클릭하면 500 에러가 발생합니다. 500 에러로 인한 메일 전송을 방지하려면 settings_local.py 파일에서 메일 보내는 부분을 전부 주석처리해주세요.

requirements.txt 미작성으로 인한 런서버 불가 문제 해결.

---

apps/review/views.py
templates/components/header.html
templates/timetable/layout.html

OTL-Dictionary -> OTL
OTL timetable로 이동 -> 삭제
timetable의 검색창 -> 삭제

navigation bar 수정

---

apps/subject/management/commands/delete-needlessLecture.py

OTL Timetable에서 필요없어서 제거시켰던 연구 과목들의 정보를 timetable.models의 ResearchLecture에 저장시키는 스크립트입니다.
Professor 정보를 제외하고는 잘 받아옴을 확인할 수 있습니다. (이것은 빠르게 수정하도록 하겠습니다.)

[거의 완성] ResearchLecture를 저장하는 script

---

apps/timetable/views.py
static/css/timetable/timetable.css
static/js/timetable/timetable.js
templates/timetable/base.html
templates/timetable/index.html

일단 덕성이형 코드를 그대로 사용하였기에 Backbone이 사용되었습니다. 나중에 바꾸던가 해야합니다.

implement timetable clicking

---

apps/timetable/models.py
apps/timetable/urls.py
apps/timetable/views.py
templates/timetable/show.html

잘못된 커밋 수정합니다.

---

apps/review/urls.py
apps/review/views.py
apps/session/sparcssso.py
apps/session/views.py
static/js/session/user_comments.js
templates/session/login_error.html
templates/session/settings.html

내가 쓴 후기들을 볼 수 있도록 할 예정입니다. 이에 이어 issue #81 를 해결해 사용자가 후기를 골라 볼 수 있도록 시스템을 좀 더 보완할 예정입니다.
로그인 에러 페이지가 저번 커밋 때 누락된 것 같아 추가합니다.
\+ 
머지되기 전에 새로운 커밋을 날렸습니다.
이제 마이페이지에 내가 본 후기 목록을 높이 350px div 안에서 5개씩 불러와서 볼 수 있습니다.
review app의 views.py에 유저가 쓴 후기 목록을 json의 형태로 보내주는 함수를 작성했고 이 함수에 접근하기 위해  review.urls.py 파일도 수정했습니다.
프론트 엔드 부분은 주로 최신 후기 보기 페이지 코드를 가져왔습니다. 하지만 기존 코드가 재활용하기 어려운 부분도 있고,작게 수정해야할 부분도 있어서 import하는 대신 복사해서 새로운 파일을 만들었습니다.

내가 쓴 후기들, 로그인 에러 페이지 + 내가 쓴 후기 보기

---

apps/review/views.py
otlplus/settings.py
otlplus/urls.py
static/js/joyride-master/joyride-2.1.css
templates/review/tutorial-sparcssso-auth.html
templates/review/tutorial-sparcssso-connect.html

pep8 안 맞는거 열심히 고쳐보려다가 양이 너무 많아 포기.
sparcs sso UI 업데이트에 맞추어 튜토리얼 작성. 
기존에 튜토리얼 박스에 잘려서 나오던 현상 어느정도 수정. next button의 모양이 어색하던 것 수정.
튜토리얼 이스터에그에 트렌드에 맞추어 도꺠비, 너의 이름은 몀대사 패러디 추가.

tutorial according to sparcs sso ui update.

---

apps/timetable/urls.py
apps/timetable/views.py
templates/timetable/update_table.html

로그인하시고,
[[base_url]/timetable/api/show]() -> 자기 lectures 보기
[[base_url]/timetable/update]() -> timetable에 lecture 추가하기 테스트 페이지 (매우 간단)
보니깐 lecture 모델에 classtime, examtime 이 foreign key로 없던데 이 문제도 나중에 상의해서 해결해야 할 것 같네요.

시간표 업데이트/확인 가능

---

templates/review/lastcomment.html
templates/review/result.html

LoadOnScroll을 할 때 코스명을 선택했을 때 undefined로 연결되면서 404 error가 되는 부분을 수정하였습니다.

Fixed LoadOnScroll Bug

---

static/css/review/insert.css
static/css/review/result.css
static/css/review/search.css
templates/review/search.html

css를 깎고 있습니다. 모바일/pc 모두 체크하고 문제 있으면 알려주세요

Fix header

---

react/src/timetable/components/Exam.js
react/src/timetable/components/Map.js
react/src/timetable/components/Summary.js

exam timetable

---

react/src/common/Scroller.js
react/src/timetable/components/Detail.js
react/src/timetable/components/ListBlock.js
react/src/timetable/components/Review.js
react/src/timetable/reducers/list.js

React etranger park

---

react/src/timetable/components/Timetable.js
react/src/timetable/components/TimetableBlock.js

block hover, blockclick, blockout complete

React bogo

---

react/src/timetable/components/Search.js
react/src/timetable/components/SearchFilter.js

Search bar is implement,
fill the filter value, 
implement autocomplete
searching by press 'enter'

Search bar implement
